### ISSUE TITLE
opinionated tool for introducing people to conventional-changelog

### ISSUE THREAD

**Issue by bcoe** [conventional-changelog-archived-repos/meta#1]
For introducing folks to the concept of a conventional-changelog, I think we should point people towards an opinionated CLI tool that defaults to `angular-style` and applies the workflow outlined in conventional-changelog-cli: 
1. Make changes
2. Commit those changes
3. Make sure Travis turns green
4. Bump version in package.json
5. conventionalChangelog
6. Commit package.json and CHANGELOG.md files
7. Tag
8. Push

It's easier to introduce folks to the value of a standardized changelog if we create a dead-simple approach for them to follow....

I'm picturing the combined functionality of `standard-changelog` and `conventional-recommended-workflow` -- `conventional-recommended-workflow` is the worst module name _ever_, we should think of something more catchy for the tool I'm describing :smile:

**Comment by bcoe** [comment]
@stevemao @nexdrew what if we merged `standard-changelog` and `conventional-recommended-workflow`, and `standard-changelog` was a bin just applied the whole recommended flow:
- folks are used to [standard](https://github.com/feross/standard) being an opinionated tool, and I think we could piggyback off @feross' naming.
- `standard-changelog` is a catchy name; it seems like if our goal is to get more projects using the approach this would be a good bin to push them to install.

**Comment by feross** [comment]
Feel free to name this `standard-whatever`. :+1: I support that. I started doing changelogs recently for a few projects and some good tooling would really come in handy.

Just be prepared for the trolls to show up and complain "But, but, you're NOT A STANDARDS BODY!! How DARE you use that name!?!" :wink:

**Comment by stevemao** [comment]
> what if we merged standard-changelog and conventional-recommended-workflow, and standard-changelog was a bin just applied the whole recommended flow:

I really don't mind. But I would like [conventional-github-releaser](https://github.com/conventional-changelog/conventional-github-releaser) embedded :)

conventional-github-releaser is automatically used if user is on github. disabled if not.

**Comment by stevemao** [comment]
Thanks @feross :)

> But, but, you're NOT A STANDARDS BODY!! How DARE you use that name!?!

Thats the reason why I created configurable `conventional-changelog` :) People were already complaining (mostly because they made a mistake in the commit message). So it changes the way how I design a tool (being more unopinionated) :( 

It's great to have @bcoe on board and in fact, the original authors wanted this to be opinionated. Since we have both `standard-changelog` and `conventional-changelog`, users have a choice :smile:

**Comment by nexdrew** [comment]
FWIW, I definitely like the idea of a zero-configuration, opinionated bin that bumps semver, generates a changelog, commits the changes, and tags a release - which is basically `conventional-recommended-workflow` without a `--preset` option. This seems like a really useful tool for authors that want to automate that part of the release process but are hesitant to adopt `semantic-release`. I think a lot of authors will quite happily conform to some opinionated conventions if it makes their lives easier.

@stevemao I was unaware of `conventional-github-releaser` until you just mentioned it. That sounds like a cool idea, but that means the tool will automatically push your git tags for you as well? I think it's just a decision of whether the tool should push to GitHub or not: if yes, then it makes sense to turn the tag into a release too; if not, then it can't auto-create the release in GitHub.

I think the nice part of **not** pushing to GitHub on behalf of the author is it still gives the author a chance to rectify mistakes locally if something goes wrong or they run it accidentally/prematurely or whatever. But, if you think folks are willing to sacrifice that for the sake of automation, I'm for it.

**Comment by stevemao** [comment]
> FWIW, I definitely like the idea of a zero-configuration, opinionated bin that bumps semver, generates a changelog, commits the changes, and tags a release - which is basically conventional-recommended-workflow without a --preset option. This seems like a really useful tool for authors that want to automate that part of the release process but are hesitant to adopt semantic-release. I think a lot of authors will quite happily conform to some opinionated conventions if it makes their lives easier.

There were about 100 issues opened about this :) I think `conventional-changelog` should play a role like `eslint` and `standard-changelog` being `standard`, which is good. Those issues are closed now and I think they are happy.

> but that means the tool will automatically push your git tags for you as well?

No, if there is no tag, it will probably error or release on the previous tag I think.

> I think the nice part of not pushing to GitHub on behalf of the author is it still gives the author a chance to rectify mistakes locally if something goes wrong or they run it accidentally/prematurely or whatever.

depends on if they have pushed the commits or not. If they have, the trouble of changing them manually would be the same.

**Comment by stevemao** [comment]
Hm...Looking at my [gist](https://gist.github.com/stevemao/280ef22ee861323993a0) again, I think `standard-changelog` being `conventional-recommended-workflow` and `conventional-github-releaser` with zero-configuration is a good idea :)

**Comment by bcoe** [comment]
@nexdrew @stevemao I like the idea of a tool that does everything for me, but doesn't push to github or to npm; personally I like having to perform a final sanity check before pushing to either of these locations -- I think it's the paranoid ops person in me.

Perhaps the difference between the `conventional-github-releaser` and `standard-changelog` is that:
- `conventional-github-releaser`: actually interacts with the GitHub API, and pushes content:
  - perhaps there's an option to push up to npm too?
- `standard-changelog`: does everything except push and publish.
  - or heck, maybe you can configure it to do so? make it a personal choice.

**Comment by stevemao** [comment]
> perhaps there's an option to push up to npm too?

I don't think npm supports release notes? If you mean publish to npm then i don't think so... `conventional-github-releaser` doesn't even do `git push` or `git push --tags` or removing previous releases. I like to keep `conventional-github-releaser` very focused. There are many other tools to do `npm publish`. Modules like `conventional-changelog`, `conventional-github-releaser` and their dependencies are less likely to be used standalone by themselves as they should only do one thing well.

> or heck, maybe you can configure it to do so?

I vote for it :+1: , `standard-changelog`, `conventional-recommended-workflow` or even [`atom-conventional-changelog`](https://github.com/conventional-changelog/atom-conventional-changelog) I made for fun are more likely to do everything for user. So whatever is convenient for them.

**Comment by stevemao** [comment]
Just some updates:
from @bcoe https://github.com/conventional-changelog/standard-version/pull/9:

> @stevemao, yes! @nexdrew and I had a discussion, we were thinking we'd keep the scope of the standard-changelog bin to just changelog generation. This bin can replace the npm version workflow, with changelog generation as part of it.

I guess you would like to see another wrapper does `recommended-workflow`?
