### ISSUE TITLE
repo transfers

### ISSUE THREAD

**Issue by stevemao** [conventional-changelog-archived-repos/meta#3]
I have transferred all my related repos. If I miss anything please comment.
Two repos are held by the angular folks.
- [ ] [grunt-conventional-changelog](https://github.com/btford/grunt-conventional-changelog)
- [x] [conventional-changelog](https://github.com/ajoslin/conventional-changelog)

**Comment by bcoe** [comment]
see: https://github.com/conventional-changelog/conventional-changelog/issues/163
