### ISSUE TITLE
Ignore beta tags?

### ISSUE THREAD

**Issue by astalker** [conventional-changelog-archived-repos/meta#7]
Is it possible that when generating the changelog to ignore certain tags. So rather than having a group of 0.1.0-beta.2 the commits would be grouped in to the next actual release? The issue I have is that commits in the beta tag can be released after a hotfix but would appear earlier in the changelog.

Re: https://github.com/conventional-changelog/conventional-changelog/blob/master/CHANGELOG.md

Perhaps it doesn't make sense but my intention is to simplify how I present my changelog

**Comment by stevemao** [comment]
have you tried https://github.com/conventional-changelog/conventional-changelog-writer#generateon?

**Comment by astalker** [comment]
I hadn't seen that but after some more investigationI think my issue is due to the fact we use tags for other things that just don't fit in to how the log should be generated. Thanks.
