### ISSUE TITLE
move to lerna repo

### ISSUE THREAD

**Issue by bcoe** [conventional-changelog-archived-repos/meta#9]
I propose that we move `conventional-changelog` to a mono-repo using lerna, and center conversation around `conventional-changelog/conventional-changelog` (the same approach used by babel):

https://github.com/conventional-changelog/conventional-changelog/pull/158

I think using a mono-repo will help speed up development on conventional-changelog; since features often span several of its libraries.

**Comment by stevemao** [comment]
Great idea! I'm in favour if most members are happy with this :)

**Comment by hutson** [comment]
That would be fine with me. There seems to be sufficient coupling between `conventional-changelog` projects that a monorepo would make it easier to do cross project refactoring.

**Comment by bcoe** [comment]
@Tapppi, @nexdrew, @ajoslin, care to add a vote? I'm have a bit of time to get the initial mono-repo over the finish line today -- and have pulled in the entire git history for each repo.

**Comment by Tapppi** [comment]
I browsed lerna a bit when you first mentioned supporting it in `standard-version`, but was put off by the idea of trying to combine such a huge number of projects as a first try.. Not a problem anymore! Amazing work, and should help a lot with bigger changes spanning multiple repos. :+1: from me

**Comment by ajoslin** [comment]
I agree, a mono-repo with Lerna is a good approach here.

I've been using Lerna heavily on a lot of projects lately and it really speeds things up compared to having many interdependent separate repositories.

**Comment by stevemao** [comment]
Just be aware that we have outstanding issues in the archived repos. Can't forget them :)

**Comment by stevemao** [comment]
Also @bcoe can you give us admin access to `conventional-changelog-archived-repos`?
I think this repo should still be in the `conventional-changelog` org.

**Comment by bcoe** [comment]
@stevemao hey; I've given you admin access to the organization `conventional-changelog-archived-repos`;

I think it's probably a good idea to keep this organization separate, so that we don't confuse people as to where to open issues. I'm happy to help move these issues over to the mono-repo (and have already begun doing so).

**Comment by stevemao** [comment]
Sure. I just meant that the meta repo (this one) could still be in `conventional-changelog` org? But if you think the meta/discussion should happen in the `conventional-changelog` repo that's fine :)

**Comment by bcoe** [comment]
@stevemao gotcha! I think what I've seen with other monorepos like babel, is that conversation centers around the top-level monorepo:

https://github.com/babel/babel
https://github.com/lerna/lerna

Are you comfortable with trying out this approach?

**Comment by stevemao** [comment]
No problem 👍

**Comment by stevemao** [comment]
@bcoe @Tapppi Could you make me as an owner? I can't close this issue... Thanks!
